server:
  servlet:
    context-path: /api
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:test_db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
